name: Generate Test Tool Artifacts
on:
  push:

env:
  TOOLS_DIR: ${{github.workspace}}/build/tools
  TOOLS_FILE_NAME: tools

jobs:
  generate-test-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      #- name: Install XZ dependency (Not required, comes with the runner)
        #run: sudo apt install xz-utils

      - name: Compile Test Tool
        run: |
          mkdir build && cd build
          cmake .. && make -j$(nproc)

      - name: Compress Test Tool
        run: |
          cd ${{env.TOOLS_DIR}}; XZ_OPT=-9; find . -type f -executable -exec tar cfJ ${{env.TOOLS_FILE_NAME}}.tar.xz {} +;
          if [ $? -eq 0 ]; then
            size=$(du -sh ${{env.TOOLS_FILE_NAME}}.tar.xz)
            echo "Tools successfully compressed: ${size}"
            mv ${{env.TOOLS_FILE_NAME}}.tar.xz ${{github.workspace}}
            exit 0
          else
            echo "Error compressing tools."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ${{env.TOOLS_FILE_NAME}}
          path: ${{env.TOOLS_FILE_NAME}}.tar.xz
          if-no-files-found: error
          compression-level: 0
          overwrite: true

